name: codeswipe_chat
version: 1.0.0
description: 'Dart functions for codeswipe chat module'
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dart_appwrite: ^8.0.0

dev_dependencies:
  lints: ^2.0.1
